name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the cheat sheet index.json
        run: python ./build.py
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
